layout_spectrum: 0.23812902599388716
typography_spectrum: 0.22905337070326995
color:
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  brandStrength: 0.38372690133897974
  lightness: 0.6622393795108368
  saturation: 0.9534762068587069
  rhythmicContrast: 0.3900199877454134
github: true
author:
  name: sungmin_roh
  email: iegojoa@hanmail.net
name: fladry
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 노성민.포스팅.한국
    url: 'https://thegrid.ai/fladry-57893/'
    type: external
title: 노성민
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/da71eeb0-8b52-4827-98fd-1ec94afd6bb6.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/da71eeb0-8b52-4827-98fd-1ec94afd6bb6.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 프로필
