typography_spectrum: 0.1519043721719691
color:
  brandColors:
    - '#979799'
    - '#FFFFFF'
    - '#0D0D0D'
    - '#A24742'
    - '#058C49'
  brandStrength: 0.8818670056937354
  lightness: 0.8416720998838617
  saturation: 0.9440544491851388
  rhythmicContrast: 0.2604964013270444
github: true
opengraph:
  type: ''
layout_spectrum: 0.8859577212692008
analytics:
  google: UA-110882097-1
author:
  name: sungmin_roh
  email: iegojoa@hanmail.net
name: fladry
url: 'https://thegrid.ai/fladry/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 노성민.포스팅.한국
    url: 'https://thegrid.ai/fladry-57893/'
    type: external
  - name: 인스타
    url: 'http://instagram.com/sungmin_roh'
    type: external
  - name: 페이스북
    url: 'https://www.facebook.com/iegojoa'
    type: external
title: S K
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/da71eeb0-8b52-4827-98fd-1ec94afd6bb6.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/da71eeb0-8b52-4827-98fd-1ec94afd6bb6.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d847d12-19e6-4b34-8662-c5f7c63728f1.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d847d12-19e6-4b34-8662-c5f7c63728f1.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: NSOK
